### ISSUE TITLE
Shannon Scores normalisation

### ISSUE THREAD

**Issue by hkoohy** [bittremieux/TCR-Classifier#1]
Hi, 
Dont you think you should have normalised shannon scores to repertoire size? Otherwise, obviously the bigger the repertoire the bigger shannon scores, that seems to be the case in table you have reported int the manuscript.
Thanks

**Comment by NDeNeuter** [comment]
Hi,

Thank you for your interest in our paper!

Our main goal in providing these metrics was to give readers a bit more insight into the structure of the data. As the Shannon diversity reflects both size and evenness of the data, it seemed a good descriptor to us. I agree that also including a normalized Shannon score to provide more information purely on the evenness would have been a good idea.
Including this metric is currently not a priority for us. Should you be interested in including this, please feel free to submit a pull request to fix this issue.

Kind regards,
Nicolas
